image: python:3.12-slim

stages:
  - test
  - deploy

default:
  before_script:
    - python --version; pip --version
    - pip install uv
    - uv venv .venv
    - source .venv/bin/activate
    - uv pip install -r requirements.txt
    - uv pip install -r requirements-dev.txt
    - uv pip install --editable .

test:
  stage: test
  script:
    - pytest -v tests
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"'

pages:
  stage: deploy
  script:
    - cd docs
    - sphinx-build -b html . ../public
    - cd ..
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'