image: python:3.12-slim

stages:
  - test
  - deploy

default:
  before_script:
    - python --version; pip --version
    - pip install virtualenv
    - virtualenv .venv
    - source .venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements-dev.txt
    - pip install --editable .

test:
  stage: test
  script:
    - pytest -v tests
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "QL-2.0"'

pages:
  stage: deploy
  script:
    - cd docs
    - sphinx-build -b html . ../public
    - cd ..
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "QL-2.0"'